<?php

include("login.php");

$drop = [
    "DROP TABLE ALLERGIES CASCADE CONSTRAINTS;",
    "DROP TABLE APPOINTMENT_INFORMATION CASCADE CONSTRAINTS;",
    "DROP TABLE BILLING_HISTORY CASCADE CONSTRAINTS;",
    "DROP TABLE BILLING_INFORMATION CASCADE CONSTRAINTS;",
    "DROP TABLE EMERGENCY_CONTACT_INFORMATION CASCADE CONSTRAINTS;",
    "DROP TABLE IMMUNIZATION_INFORMATION CASCADE CONSTRAINTS;",
    "DROP TABLE INSURANCE_INFORMATION CASCADE CONSTRAINTS;",
    "DROP TABLE MEDICAL_HISTORY CASCADE CONSTRAINTS;",
    "DROP TABLE MEDICAL_STAFF CASCADE CONSTRAINTS;",
    "DROP TABLE PATIENT_CONTACT_INFORMATION CASCADE CONSTRAINTS;",
    "DROP TABLE PATIENT_INFORMATION CASCADE CONSTRAINTS;",
    "DROP TABLE PRESCRIPTIONS_AND_MEDICATION CASCADE CONSTRAINTS;",
    "DROP TABLE PREVIOUS_OPERATIONS CASCADE CONSTRAINTS;",
];

foreach ($drop as $query) {
    if (mysqli_query($conn, $query)) {
        echo "Table " . $query . "dropped.";
    } else {
        echo "Error dropping". mysqli_error($conn) ;
    }
}

mysqli_close($conn);
