<?php include ('login.php'); ?>

<div style="color:#14888E; text-align:center;">

<?php


$tables = [
"ALLERGIES" => "CREATE TABLE ALLERGIES (	
    ALLERGIESID CHAR(10 BYTE), 
	TYPE VARCHAR2(255 BYTE), 
	SEVERITY VARCHAR2(50 BYTE), 
	ADDITIONALCOMMENTS VARCHAR2(255 BYTE)
   )",

"APPOINTMENT_INFORMATION" => "CREATE TABLE APPOINTMENT_INFORMATION(	
    APPOINTMENT_ID CHAR(10 BYTE),
	PATIENTID CHAR(16 BYTE),
	DATEOFAPPOINTMENT DATE,
	REASONFORVISIT VARCHAR2(255 BYTE),
	PHYSICIAN VARCHAR2(50 BYTE),
	DIAGNOSIS VARCHAR2(255 BYTE),
	TREATMENTPLAN VARCHAR2(255 BYTE)
   )",

"BILLING_HISTORY" => "CREATE TABLE BILLING_HISTORY(	
    BILLSID CHAR(10 BYTE),
	CHARGENAME VARCHAR2(50 BYTE),
	DATEOFCHARGE DATE,
	ORIGINALCHARGE NUMBER(7,2),
	OUTSTANDINGPAYMENT NUMBER(7,2),
	PAID NUMBER(7,2)
   )",

"BILLING_INFORMATION" => "CREATE TABLE BILLING_INFORMATION(	
    BILLINGINFORMATIONID CHAR(10 BYTE),
    ADDRESS VARCHAR2(255 BYTE),
    CARDNUMBER CHAR(16 BYTE),
    BILLSID CHAR(10 BYTE),
    INSURANCECOVERAGEID CHAR(10 BYTE)
    )",

"EMERGENCY_CONTACT" => "CREATE TABLE EMERGENCY_CONTACT(	
    EMERGENCYCONTACTSID CHAR(10 BYTE), 
	FULLNAME VARCHAR2(50 BYTE), 
	PHONENUMBER NUMBER, 
	EMAIL VARCHAR2(50 BYTE), 
	SECONDARYPHONENUMBER NUMBER
   )",

"EMERGENCY_RELATIONS" => "CREATE TABLE EMERGENCY_RELATIONS(	
    EMERGENCYCONTACTSID CHAR(10 BYTE), 
	PATIENTID CHAR(16 BYTE), 
	RELATION VARCHAR2(50 BYTE), 
	PRIORITY VARCHAR2(3 BYTE)
   )",

"INSURANCE_INFORMATION" => "CREATE TABLE INSURANCE_INFORMATION(	
    INSURANCECOVERAGEID CHAR(10 BYTE),
	INSURANCEPROVIDER VARCHAR2(50 BYTE),
	POLICYNUMBER VARCHAR2(20 BYTE),
	COVERAGETYPE VARCHAR2(100 BYTE),
	CURRENTCOVERAGE NUMBER
   )",


"MEDICAL_HISTORY" => "CREATE TABLE MEDICAL_HISTORY(	
    PATIENTID CHAR(16 BYTE),
	ALLERGIESID CHAR(10 BYTE),
	FAMILYHISTORY VARCHAR2(255 BYTE),
	PREVIOUSOPERATIONSID CHAR(10 BYTE),
	PRESCRIPTIONSID CHAR(10 BYTE),
	IMMUNIZATIONSID CHAR(10 BYTE),
	COMMENTS VARCHAR2(255 BYTE)
   )",

"MEDICAL_STAFF" => "CREATE TABLE MEDICAL_STAFF(	
    ID CHAR(16 BYTE),
	FULLNAME VARCHAR2(50 BYTE),
	ROLE VARCHAR2(50 BYTE)
   )",

   
"PATIENT_CONTACT_INFORMATION" => "CREATE TABLE PATIENT_CONTACT_INFORMATION(	
    PATIENTID CHAR(16 BYTE),
    ADDRESS VARCHAR2(255 BYTE),
    EMAIL VARCHAR2(50 BYTE),
    PHONENUMBER NUMBER
)",


"PATIENT_INFORMATION" => "CREATE TABLE PATIENT_INFORMATION(	
    PATIENTID CHAR(16 BYTE),
	FULLNAME VARCHAR2(50 BYTE),
	HEALTHCARDNUMBER CHAR(10 BYTE),
	SEX VARCHAR2(15 BYTE),
	GENDER VARCHAR2(25 BYTE),
	DATEOFBIRTH DATE,
	DATEOFDEATH DATE,
	BLOODTYPE VARCHAR2(5 BYTE),
	BILLINGINFORMATIONID CHAR(10 BYTE),
	EMERGENCYCONTACTSID CHAR(10 BYTE)
)",


"PRESCRIPTIONS_AND_MEDICATION" => "CREATE TABLE PRESCRIPTIONS_AND_MEDICATION(	
    PRESCRIPTIONSID CHAR(10 BYTE),
	CURRENTLYPRESCRIBED NUMBER(1,0) DEFAULT 0,
	MEDICATIONID CHAR(8 BYTE),
	PRESCRIPTIONNAME VARCHAR2(100 BYTE),
	DOSAGE VARCHAR2(50 BYTE),
	FREQUENCY NUMBER,
	DATEPRESCRIBED DATE,
	REFILLS_REMAINING NUMBER,
	PRESCRIBINGPHYSICIAN VARCHAR2(50 BYTE)
)",

"PREVIOUS_OPERATIONS" => "CREATE TABLE PREVIOUS_OPERATIONS(	
    PREVIOUSOPERATIONSID CHAR(10 BYTE),
	OPERATIONDATE DATE,
	SURGERYTYPE VARCHAR2(50 BYTE),
	INVASIVENESS VARCHAR2(30 BYTE),
	DURATIONOFSTAY VARCHAR2(50 BYTE),
	DATEOFRELEASE DATE,
	ATTENDINGPHYSICIAN VARCHAR2(50 BYTE),
	COMPLICATIONS VARCHAR2(255 BYTE),
	NOTES VARCHAR2(255 BYTE)
)"
];


foreach ($tables as $tablename => $query) {
    $stid = oci_parse($conn, $query);
    if (oci_execute($stid)) {
        echo "<div>Table '$tablename' Successfully Created.</div>";
    } else {
        $error = oci_error($stid);
        echo "<div>Error Creating Table '$tablename': " . htmlentities($error['message']) . "</div>";
    }

    oci_free_statement($stid);
}

oci_close($conn);

?>

</div>
