<?php

include("login.php");

$drop = [
    "DROP TABLE ALLERGIES CASCADE CONSTRAINTS;",
    "DROP TABLE APPOINTMENT_INFORMATION CASCADE CONSTRAINTS;",
    "DROP TABLE BILLING_HISTORY CASCADE CONSTRAINTS;",
    "DROP TABLE BILLING_INFORMATION CASCADE CONSTRAINTS;",
    "DROP TABLE EMERGENCY_CONTACT_INFORMATION CASCADE CONSTRAINTS;",
    "DROP TABLE IMMUNIZATION_INFORMATION CASCADE CONSTRAINTS;",
    "DROP TABLE INSURANCE_INFORMATION CASCADE CONSTRAINTS;",
    "DROP TABLE MEDICAL_HISTORY CASCADE CONSTRAINTS;",
    "DROP TABLE MEDICAL_STAFF CASCADE CONSTRAINTS;",
    "DROP TABLE PATIENT_CONTACT_INFORMATION CASCADE CONSTRAINTS;",
    "DROP TABLE PATIENT_INFORMATION CASCADE CONSTRAINTS;",
    "DROP TABLE PRESCRIPTIONS_AND_MEDICATION CASCADE CONSTRAINTS;",
    "DROP TABLE PREVIOUS_OPERATIONS CASCADE CONSTRAINTS;",
];

foreach ($drop as $query) {
    $stmt = oci_parse($conn, $query); // Prepare the SQL statement
    if (oci_execute($stmt)) {
        echo "Table dropped successfully: $query<br>";
    } else {
        $error = oci_error($stmt);
        echo "Error dropping table: " . $error['message'] . "<br>";
    }
}

oci_close($conn); // Close the Oracle connection
